[package]
name = "my_running"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.44"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2.1"
regex = "1"